### PR TITLE
Update Signup.Java

### PR DESCRIPTION
**Pull request by DakshitChopra**
Fixed a typo

### CODE REVIEW

**Comment by DakshitChopra** [comment]
It wasn't intentional. I didn't know that it was inappropriate initially, so later I closed this PR myself after realizing my mistake.

**Comment by amar-psr** [comment]
No, problem

**Comment by amar-psr** [comment]
If you want to contribute, please check if the pr is directly merge able to the master branch

**Comment by DakshitChopra** [comment]
Actually, I closed my other PR too, by mistake. Sorry for the inconvenience.
Thank you for your time. I will make a good pull request next time. :").

**Pull request closed without merging**
